language: android
android:
    components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y sendemail
script:
    - ./gradlew clean build
    - travis_wait 50 bash IntegrationTesting.sh
